name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          appdir: "backend"
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "ca-manager-api"
          heroku_email: ${{secrets.Email}}
          branch: "master"